### PR TITLE
Plugin overhauled

### PR DESCRIPTION
**Pull request by darealshinji**
Not entirely sure if the hook stuff is done right.

### CODE REVIEW

**Comment by TheAssassin** [comment]
The hook directory needs to be created inside the AppDir while the plugin runs. The layout you implemented here would be correct, though.

The hook file assumes the current working directory is set to the AppDir, but that is not done by either component. The environment variable `$APPDIR` points to the mountpoint directory.

**Comment by darealshinji** [comment]
The hook file was updated.

**Comment by darealshinji** [comment]
I have rewritten checkrt but I can make a new PR.

**Comment by TheAssassin** [comment]
Maybe we can just integrate a plugin script in your repository?

**Pull request closed without merging**
