### PR TITLE
Source any files in apprun-hooks before running the executable

### PR DESCRIPTION
**Pull request by hcorion**
This fixes issues when running multiple plugins with checkrt like qt or gstreamer

### CODE REVIEW

**Comment by TheAssassin** [comment]
This project should probably just stop distributing its own `AppRun.sh` and generate a hook script instead. linuxdeploy's autogenerated `AppRun` already sources all the hooks.

What do you think?

**Comment by hcorion** [comment]
That seems reasonable to me, I'll work on that 👍

**Comment by hcorion** [comment]
I see a setup was actually already attempted here https://github.com/linuxdeploy/linuxdeploy-plugin-checkrt/pull/2 for properly using apprun-hooks for checkrt.
@darealshinji what's the status on this? Did you need any help hooking up a plugin script in your original repo?

**Comment by TheAssassin** [comment]
Now that you mention it, I think @darealshinji liked the idea of including the plugin script in the upstream repository...

**Comment by darealshinji** [comment]
> This project should probably just stop distributing its own `AppRun.sh` and generate a hook script instead. linuxdeploy's autogenerated `AppRun` already sources all the hooks.
> 
> What do you think?

Sounds good. A PR from anyone is welcome though.

**Comment by darealshinji** [comment]
I'm currently rewriting it as a linuxdeploy plugin:
https://github.com/darealshinji/AppImageKit-checkrt/tree/dev

It will be merged into the master branch once I'm done with testing and writing a new readme file.

**Comment by TheAssassin** [comment]
Looks really good to me, really looking forward to testing it. Making upstream a proper plugin for linuxdeploy is the best possible option.

I'll archive this repository as soon as the new version is done. Alternatively, you can take over this repository as a maintainer if you like.

In any case, we should update https://github.com/linuxdeploy/awesome-linuxdeploy eventually.

**Pull request closed without merging**
